name: Synthia
version: "0.1.0"
slug: synthia
description: A personal AI assistant running as a Home Assistant add-on.
url: "https://github.com/danhajduk/syntia-addon/tree/main/syntia"

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

init: false
startup: services
boot: auto
homeassistant_api: true
host_network: true

options:
  log_level: info

schema:
  log_level: str

