log_level:
  name: Log Level
  description: Set the logging level for Synthia
  selector:
    select:
      options:
        - info
        - debug
        - warning
        - error
        - critical

enable_notifications:
  name: Enable Notifications
  description: Whether Synthia should send notifications
  selector:
    boolean: {}

openai_api_key:
  name: OpenAI API Key
  description: Paste your OpenAI API key here
  selector:
    text:
      type: password

assistant_id:
  name: OpenAI Assistant ID
  description: Your dedicated Assistant ID from OpenAI
  selector:
    text:
      type: text

admin_api_key:
  name: OpenAI Admin API Key
  description: Used for usage reporting only (must be from a billing admin)
  selector:
    text:
      type: password
